In [1]:
import json, random, math
from datetime import datetime, timedelta
from pathlib import Path

import numpy as np
import pandas as pd

In [2]:
user_profile_df = pd.DataFrame([{
    "id": "9999",  # Manual ID
    "name": "Artemis",
    "email": "artemis@example.com",
    "age": 27,
    "sex": "Male",
    "weight_kg": 68,
    "height_cm": 173,
    "activity_level": "Moderately Active",  # Must match expected strings
    "exercise_frequency_per_week": 4
}])

user_profile_df

,id,name,email,age,sex,weight_kg,height_cm,activity_level,exercise_frequency_per_week
0,9999,Artemis,artemis@example.com,27,Male,68,173,Moderately Active,4

In [3]:
# 🎯 Your Health Goals
user_preferences_df = pd.DataFrame([{
    'user_id': 9999,
    "health_conditions": ["none"],  # list of conditions
    "goal_type": "muscle_gain",      # match with what calculations expects
    "motivation": "Increase strength and energy",
    "dietary_restrictions": "Shellfish",
    "preferred_cuisines": "Mediterranean, Indian"
}])

user_preferences_df

,user_id,health_conditions,goal_type,motivation,dietary_restrictions,preferred_cuisines
0,9999,[none],muscle_gain,Increase strength and energy,Shellfish,"Mediterranean, Indian"

In [4]:
IMMUTABLE_COLS = ["id", "name", "sex", "height_cm"]
MUTABLE_COLS   = ["age", "weight_kg", "activity_level",
                  "exercise_frequency_per_week"]

immutable_profile = user_profile_df[IMMUTABLE_COLS].iloc[0].to_dict()
mutable_profile   = user_profile_df[MUTABLE_COLS].iloc[0].to_dict()

nutrition_targets = pd.DataFrame([{
    "user_id": 9999,
    "optimal_calories": 2876.97,
    "protein_g": 251.73,
    "carbs_g":   287.70,
    "fat_g":      79.92,
    "ibw_kg":     70.15,
    "health_conditions": ["none"],
    "goals": ["muscle_gain"],
    "motivation": "Increase strength and energy"
}]).iloc[0].to_dict()

print("✅ immutable_profile:", immutable_profile)
print("✅ mutable_profile:",   mutable_profile)
print("✅ nutrition_targets:", {k:round(v,2) if isinstance(v,float) else v
                               for k,v in nutrition_targets.items()})

✅ immutable_profile: {'id': '9999', 'name': 'Artemis', 'sex': 'Male', 'height_cm': 173}
✅ mutable_profile: {'age': 27, 'weight_kg': 68, 'activity_level': 'Moderately Active', 'exercise_frequency_per_week': 4}
✅ nutrition_targets: {'user_id': 9999, 'optimal_calories': 2876.97, 'protein_g': 251.73, 'carbs_g': 287.7, 'fat_g': 79.92, 'ibw_kg': 70.15, 'health_conditions': ['none'], 'goals': ['muscle_gain'], 'motivation': 'Increase strength and energy'}

In [5]:
from datetime import datetime, timedelta

# 🗓️ Set the starting date (today)
today = datetime.now()

# ✍️ Manually define your meals for each day
manual_meals = [
    # Format: (day_offset, meal_time (hh:mm), meal_type, meal_name)
    (6, "08:00", "Breakfast", "Mixed nuts and watermelon"),
    (6, "13:00", "Lunch", "Grilled chicken salad"),
    (6, "19:30", "Dinner", "Matar paneer with roti"),
    (6, "22:00", "Snack", "Protein bar"),
    
    (5, "09:00", "Breakfast", "Greek yogurt with berries"),
    (5, "12:30", "Lunch", "Matar Paneer with Rice"),
    (5, "15:00", "Snack", "Grapes"),
    (5, "20:00", "Dinner", "Vegetable stir fry"),
    
    (4, "08:30", "Breakfast", ""),
    (4, "14:00", "Lunch", "2 burgers"),
    (4, "19:00", "Dinner", "Noodles with mixed vegetables and eggs"),
    (4, "22:00", "Snack", "Protein Shake"),
    
    (3, "08:30", "Breakfast", ""),
    (3, "14:00", "Lunch", "Chicken curry with brown rice"),
    (3, "19:00", "Dinner", "Rice with chicken curry"),

    (2, "08:30", "Breakfast", "glass of milk"),
    (2, "14:00", "Lunch", "Rice with chicken curry"),
    (2, "19:00", "Dinner", "Kebab and 3 rotis"),

    (1, "08:30", "Breakfast", "A Banana"),
    (1, "14:00", "Lunch", "Kebab and 3 rotis"),
    (1, "17:00", "Snack", "Some mixed nuts"),
    (1, "19:00", "Dinner", "Rice, dal and cauliflower fry"),
    (1, "22:00", "Snack", "Peanut butter and banana smoothie"),

    (0, "08:30", "Breakfast", ""),
    (0, "14:00", "Lunch", "Rice, dal and omelette"),
    (0, "19:00", "Dinner", "Rice, dal and omelette"),
    
]

# 🍴 Build list of meal logs
meal_logs = []

for day_offset, meal_time_str, meal_type, meal_name in manual_meals:
    meal_datetime = (today - timedelta(days=day_offset)).replace(
        hour=int(meal_time_str.split(":")[0]),
        minute=int(meal_time_str.split(":")[1]),
        second=0, microsecond=0
    )
    meal_logs.append({
        "timestamp": meal_datetime,
        "day": day_offset,
        "meal_name": meal_name,
        "meal_type": meal_type,
        "user_id": 9999  # Your custom user id
    })

# 🍽️ Create DataFrame
user_meals_df = pd.DataFrame(meal_logs).sort_values(by=["timestamp"]).reset_index(drop=True)

# 🖥️ Display
user_meals_df

,timestamp,day,meal_name,meal_type,user_id
0,2025-04-28 08:00:00,6,Mixed nuts and watermelon,Breakfast,9999
1,2025-04-28 13:00:00,6,Grilled chicken salad,Lunch,9999
2,2025-04-28 19:30:00,6,Matar paneer with roti,Dinner,9999
3,2025-04-28 22:00:00,6,Protein bar,Snack,9999
4,2025-04-29 09:00:00,5,Greek yogurt with berries,Breakfast,9999
5,2025-04-29 12:30:00,5,Matar Paneer with Rice,Lunch,9999
6,2025-04-29 15:00:00,5,Grapes,Snack,9999
7,2025-04-29 20:00:00,5,Vegetable stir fry,Dinner,9999
8,2025-04-30 08:30:00,4,,Breakfast,9999
9,2025-04-30 14:00:00,4,2 burgers,Lunch,9999
10,2025-04-30 19:00:00,4,Noodles with mixed vegetables and eggs,Dinner,9999
11,2025-04-30 22:00:00,4,Protein Shake,Snack,9999
12,2025-05-01 08:30:00,3,,Breakfast,9999
13,2025-05-01 14:00:00,3,Chicken curry with brown rice,Lunch,9999
14,2025-05-01 19:00:00,3,Rice with chicken curry,Dinner,9999
15,2025-05-02 08:30:00,2,glass of milk,Breakfast,9999
16,2025-05-02 14:00:00,2,Rice with chicken curry,Lunch,9999
17,2025-05-02 19:00:00,2,Kebab and 3 rotis,Dinner,9999
18,2025-05-03 08:30:00,1,A Banana,Breakfast,9999
19,2025-05-03 14:00:00,1,Kebab and 3 rotis,Lunch,9999
20,2025-05-03 17:00:00,1,Some mixed nuts,Snack,9999
21,2025-05-03 19:00:00,1,"Rice, dal and cauliflower fry",Dinner,9999
22,2025-05-03 22:00:00,1,Peanut butter and banana smoothie,Snack,9999
23,2025-05-04 08:30:00,0,,Breakfast,9999
24,2025-05-04 14:00:00,0,"Rice, dal and omelette",Lunch,9999
25,2025-05-04 19:00:00,0,"Rice, dal and omelette",Dinner,9999

In [ ]:
import os, json, time, requests
from tqdm.auto import tqdm
from dotenv import load_dotenv  # ✅ You forgot this import
import sys

# ✅ Load .env file (make sure the path is correct)
load_dotenv("../.env", override=True)

# ✅ Retrieve secrets
EDAMAM_APP_ID  = os.getenv("EDAMAM_APP_ID")
EDAMAM_APP_KEY = os.getenv("EDAMAM_APP_KEY")

print("✅ Loaded:", EDAMAM_APP_ID, EDAMAM_APP_KEY)

def query_edamam(meal_name: str, retries: int = 2, sleep: int = 2) -> dict:
    """Return Edamam Nutrition‑Details JSON for *one* meal title."""
    url     = "https://api.edamam.com/api/nutrition-details"
    headers = {"Content-Type": "application/json"}
    payload = {"title": meal_name[:60],          # max 60 chars per docs
               "ingr": [f"1 serving {meal_name}"]}
    params  = {"app_id": EDAMAM_APP_ID, "app_key": EDAMAM_APP_KEY}

    for attempt in range(retries):
        resp = requests.post(url, headers=headers, params=params, json=payload, timeout=15)
        if resp.status_code == 200:
            return resp.json()
        if resp.status_code in (429, 500) and attempt < retries-1:
            time.sleep(sleep * (attempt+1))
            continue
        print(f"⚠️  Edamam {resp.status_code}: {resp.text[:120]}...")
        return {}          # graceful fail
    return {}

# 🗄️ Simple in‑memory cache (replace with Redis or SQLite for persistence)
NUTRI_CACHE = {}

macro_cols = ["kcal","protein_g","carbs_g","fat_g"]
user_meals_df[macro_cols] = np.nan      # initialize columns

for idx, row in tqdm(user_meals_df.iterrows(), total=len(user_meals_df), desc="Edamam"):
    title = row["meal_name"].strip()
    if not title:
        continue                        # blank meals stay NaN

    if title not in NUTRI_CACHE:
        data = query_edamam(title)
        NUTRI_CACHE[title] = data

    data = NUTRI_CACHE[title]
    if not data:
        continue                        # leave NaN if lookup failed

    user_meals_df.loc[idx, "kcal"]       = data.get("calories")
    user_meals_df.loc[idx, "protein_g"]  = (data.get("totalNutrients", {})
                                               .get("PROCNT", {})
                                               .get("quantity"))
    user_meals_df.loc[idx, "carbs_g"]    = (data.get("totalNutrients", {})
                                               .get("CHOCDF", {})
                                               .get("quantity"))
    user_meals_df.loc[idx, "fat_g"]      = (data.get("totalNutrients", {})
                                               .get("FAT", {})
                                               .get("quantity"))

# 🖥️  Show what we got
user_meals_df

In [23]:
import pandas as pd

# Define enrichment function for vague meal names
def enrich_meal_name(name: str) -> str:
    name = name.lower()
    if "protein bar" in name:
        return "1 chocolate protein bar"
    if "burger" in name:
        return "2 grilled beef burgers with cheese and lettuce"
    if "shake" in name:
        return "1 glass of chocolate protein shake with milk"
  
    return name

# Apply function safely to each meal_name (handle NaNs and blank entries)
user_meals_df["meal_name"] = user_meals_df["meal_name"].fillna("").apply(
    lambda x: enrich_meal_name(x.strip()) if x.strip() else ""  # keep blanks for skipped logic
)
user_meals_df.dropna(subset=["kcal"], inplace=True)  # remove empty meal names
user_meals_df

,timestamp,day,meal_name,meal_type,user_id,kcal,protein_g,carbs_g,fat_g
0,2025-04-28 08:00:00,6,mixed nuts and watermelon,Breakfast,9999,290.0,8.33800,28.7560,18.6100
1,2025-04-28 13:00:00,6,grilled chicken salad,Lunch,9999,537.0,46.50000,0.0000,37.7500
2,2025-04-28 19:30:00,6,matar paneer with roti,Dinner,9999,115.0,13.09800,3.9884,5.0740
3,2025-04-28 22:00:00,6,1 chocolate protein bar,Snack,9999,69.0,0.60900,9.2655,4.3500
4,2025-04-29 09:00:00,5,greek yogurt with berries,Breakfast,9999,125.0,10.51200,4.7520,7.6320
5,2025-04-29 12:30:00,5,matar paneer with rice,Lunch,9999,115.0,13.09800,3.9884,5.0740
6,2025-04-29 15:00:00,5,grapes,Snack,9999,86.0,0.90720,22.8060,0.2016
7,2025-04-29 20:00:00,5,vegetable stir fry,Dinner,9999,32.0,1.49850,6.0750,0.2340
9,2025-04-30 14:00:00,4,2 grilled beef burgers with cheese and lettuce,Lunch,9999,112.0,6.41200,0.9436,9.3240
10,2025-04-30 19:00:00,4,noodles with mixed vegetables and eggs,Dinner,9999,40.0,2.12380,7.5932,0.2050
11,2025-04-30 22:00:00,4,1 glass of chocolate protein shake with milk,Snack,9999,148.0,7.68600,11.7120,7.9300
13,2025-05-01 14:00:00,3,chicken curry with brown rice,Lunch,9999,68.0,1.42500,14.4780,0.5092
15,2025-05-02 08:30:00,2,glass of milk,Breakfast,9999,148.0,7.68600,11.7120,7.9300
17,2025-05-02 19:00:00,2,kebab and 3 rotis,Dinner,9999,201.0,7.61600,31.5520,5.0660
18,2025-05-03 08:30:00,1,a banana,Breakfast,9999,112.0,1.37340,28.7280,0.4158
19,2025-05-03 14:00:00,1,kebab and 3 rotis,Lunch,9999,201.0,7.61600,31.5520,5.0660
20,2025-05-03 17:00:00,1,some mixed nuts,Snack,9999,206.0,6.63000,7.6160,18.1900
21,2025-05-03 19:00:00,1,"rice, dal and cauliflower fry",Dinner,9999,533.0,19.28955,110.4333,1.2255
22,2025-05-03 22:00:00,1,peanut butter and banana smoothie,Snack,9999,303.0,8.47740,35.8640,16.8638
24,2025-05-04 14:00:00,0,"rice, dal and omelette",Lunch,9999,168.0,11.80800,30.4320,0.5088
25,2025-05-04 19:00:00,0,"rice, dal and omelette",Dinner,9999,168.0,11.80800,30.4320,0.5088

In [25]:
# ▢ Cell : Build clean history_summary from real macros
from datetime import datetime, timedelta
from sklearn.metrics.pairwise import cosine_similarity
from sentence_transformers import SentenceTransformer
import numpy as np

# 1️⃣  Ensure dtypes & clean blanks
for col in ["kcal","protein_g","carbs_g","fat_g"]:
    user_meals_df[col] = pd.to_numeric(user_meals_df[col], errors="coerce")

clean_df = user_meals_df.dropna(subset=["meal_name", "kcal"])   # drop rows with no food or macros
clean_df["timestamp"] = pd.to_datetime(clean_df["timestamp"])

# 2️⃣  7‑day window
WINDOW_DAYS = 7
cutoff      = datetime.now() - timedelta(days=WINDOW_DAYS)
recent      = clean_df[clean_df["timestamp"] >= cutoff].copy()

# 3️⃣  Daily macro totals → mean vector
daily_macro = (recent
               .groupby(recent["timestamp"].dt.date)[["kcal","protein_g","carbs_g","fat_g"]]
               .sum())
history_nutri_vector = daily_macro.mean().round(1).to_dict()

# 4️⃣  SBERT flavour embedding
sbert = SentenceTransformer("all-MiniLM-L6-v2")     # fast, 384‑d
embeddings = sbert.encode(recent["meal_name"].tolist(),
                          normalize_embeddings=True)
history_flavor_vector = embeddings.mean(axis=0)     # numpy

# 5️⃣  Variety histogram (reuse your SBERT / LLM cuisine guesser)
def guess_cuisine(title:str) -> str:
    # quick SBERT centroid trick (see previous answer) – adjust as desired
    seeds = {"Indian":["dal","paneer","roti"], "Mediterranean":["greek","hummus","falafel"],
             "Asian":["noodles","ramen","sushi"], "Other":[]}
    centroids = {k: sbert.encode(v, normalize_embeddings=True).mean(axis=0)
                 for k,v in seeds.items() if v}
    vec = sbert.encode(title, normalize_embeddings=True)
    sims = {k: cosine_similarity([vec],[cent])[0,0] for k,cent in centroids.items()}
    return max(sims, key=sims.get, default="Other")

recent["cuisine"] = recent["meal_name"].apply(guess_cuisine)
variety_hist = recent["cuisine"].value_counts(normalize=True).to_dict()

# # 6️⃣  Health flags (needs compute_health_flags from earlier)
# user_pref_row  = user_preferences_df.iloc[0].to_dict()
# flags = compute_health_flags(user_pref_row,
#                              aggregate_nutrients(recent),   # helper from previous reply
#                              weight_kg=mutable_profile["weight_kg"])

# 7️⃣  Assemble summary
history_summary = {
    "nutri_vector": history_nutri_vector,
    "flavor_vector": history_flavor_vector.tolist(),
    "variety_hist": variety_hist,
    "health_flags": {"sodium_over": False, "protein_low": False},
}

print("📊 history_summary")
pd.json_normalize(history_summary).T

📊 history_summary

                                                                            0
flavor_vector               [-0.03976873308420181, -0.013105497695505619, ...
nutri_vector.kcal                                                       539.6
nutri_vector.protein_g                                                   27.8
nutri_vector.carbs_g                                                     61.8
nutri_vector.fat_g                                                       21.8
variety_hist.Asian                                                   0.666667
variety_hist.Indian                                                  0.190476
variety_hist.Mediterranean                                           0.142857
health_flags.sodium_over                                                False
health_flags.protein_low                                                False

In [ ]:
from google import genai
import os 
from google.genai import types 
# Your API key
from dotenv import load_dotenv  
import sys

# ✅ Load .env file (make sure the path is correct)
load_dotenv("../.env", override=True)

GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
GEMINI_MODEL = "models/gemini-2.0-flash-lite"

client = genai.Client(api_key=GEMINI_API_KEY)

# ===========================================================
# 2. GEMINI HELPERS 
# ===========================================================
def _content_user(text):                         # ↓ single user role
    return types.Content(role="user",
                         parts=[types.Part(text=text)])

def call_gemini(one_user_string: str,
                temperature=0.3,
                max_tokens=512) -> str:
    resp = client.models.generate_content(
        model=GEMINI_MODEL,
        contents=[_content_user(one_user_string)],
        config=types.GenerateContentConfig(
            temperature=temperature,
            max_output_tokens=max_tokens
        )
    )
    return resp.candidates[0].content.parts[0].text

def gemini_json(schema: dict, payload: dict,
                temperature=0.3, max_tokens=512) -> dict:
    prompt = ("You are a dietitian model. Respond ONLY with JSON matching "
              "this schema:\n"
              + json.dumps(schema, indent=2) +
              "\n\n### INPUT\n" +
              json.dumps(payload))
    raw = call_gemini(prompt, temperature, max_tokens)
    return json.loads(re.search(r"\{.*\}", raw, re.S).group())

# ===========================================================
# 3. PLANNER INTENT  (JSON)
# ===========================================================
PLANNER_SCHEMA = {
  "goal_today": "string",
  "target_delta": {"kcal":"integer","protein_g":"integer",
                   "carbs_g":"integer","fat_g":"integer"},
  "meal_template":[{"meal":"string","cuisine":"string"}]
}

intent_json = gemini_json(
    schema=PLANNER_SCHEMA,
    payload={"profile": mutable_profile,
             "targets": nutrition_targets,
             "history": history_summary},
    temperature=0.35, max_tokens=600)
print("🗂️ intent_json\n", json.dumps(intent_json, indent=2))

🗂️ intent_json
 {
  "goal_today": "Consume a balanced diet to support muscle gain while staying within calorie targets.",
  "target_delta": {
    "kcal": 2337,
    "protein_g": 223.93,
    "carbs_g": 225.8,
    "fat_g": 58.12
  },
  "meal_template": [
    {
      "meal": "Breakfast",
      "cuisine": "Indian"
    },
    {
      "meal": "Lunch",
      "cuisine": "Asian"
    },
    {
      "meal": "Dinner",
      "cuisine": "Mediterranean"
    }
  ]
}

In [ ]:
# ▢ Cell : extract 5 candidate meals from test_users.csv
import re, json, pandas as pd
from pathlib import Path


CSV_PATH = "/home/artemis/project/hobbes_meal_rec/data/test_users.csv"   # adjust if needed
TARGET_UID = 9999                      # which user row to parse

df   = pd.read_csv(CSV_PATH)
row  = df.loc[df["user_id"]==TARGET_UID].iloc[0]

# 1️⃣  Yank JSON from the raw_output column (inside ```json ... ```)
m = re.search(r"\{.*\}", row["raw_output"], re.S)
assert m, "Could not find JSON in raw_output!"
data = json.loads(m.group())

# 2️⃣  Build candidate_meals list (take first 5 meals)
candidate_meals = []
for meal in data["meals"][:5]:
    macros = meal["macros"]
    candidate_meals.append({
        "meal_slot": meal["label"],
        "title":      meal["name"],
        "kcal":       macros["calories"],
        "protein_g":  macros["protein_g"],
        "carbs_g":    macros["carbs_g"],
        "fat_g":      macros["fat_g"],
    })

print("✅ Parsed candidate meals")
pd.DataFrame(candidate_meals)[["meal_slot","title","kcal","protein_g"]]

# using previously‑defined scoring 
cand_df = pd.DataFrame(candidate_meals)

cand_df["taste"] = cand_df["title"].apply(
    lambda t: cosine_similarity(
        [sbert.encode(t, normalize_embeddings=True)],
        [np.array(history_summary["flavor_vector"])]
     )[0,0]
)
cand_df["macro"] = cand_df.apply(
    lambda r: 1/(1+abs(r["protein_g"]-nutrition_targets["protein_g"]/3)), axis=1)
cand_df["score"] = 0.6*cand_df["taste"] + 0.4*cand_df["macro"]

ranked_meals = (cand_df
                .sort_values("score", ascending=False)
                .to_dict(orient="records"))

print("\n🏆  Ranked candidate meals")
display(cand_df[["meal_slot","title","kcal","protein_g","score"]])

✅ Parsed candidate meals

🏆  Ranked candidate meals

,meal_slot,title,kcal,protein_g,score
0,Breakfast,Oatmeal with Berries and Nuts,580,20.0,0.401256
1,Lunch,Lentil Soup with Whole-Wheat Bread and Salad,890,40.0,0.297726
2,Evening Snack,Apple slices with Peanut Butter,302,10.0,0.325206
3,Dinner,Chicken Stir-fry with Brown Rice,1030,80.1,0.419102

In [46]:
voice_prompt = json.dumps({"intent": intent_json,
                           "meals":  ranked_meals}, indent=2)
chat_reply   = call_gemini(voice_prompt, temperature=0.55, max_tokens=220)
print(chat_reply)

Okay, I can help you analyze this meal plan. Here's a breakdown and some suggestions:

**Overall Assessment:**

*   **Calorie Deficit:** The provided meals total 2802 calories, which is above the target of 2337, resulting in a calorie surplus.
*   **Macronutrient Imbalance:** The plan is significantly exceeding the target calories and has an imbalance in macronutrients.

**Detailed Analysis:**

*   **Calories:** The total calories are too high.
*   **Protein:** The protein intake is low.
*   **Carbohydrates:** The carbohydrate intake is close to the target.
*   **Fats:** The fat intake is close to the target.

**Recommendations and Adjustments:**

1.  **Prioritize Calorie Adjustment:** The most important thing is to bring the total calories down.
    *   **Reduce Portion Sizes:** Consider reducing the portion sizes of the meals.
    *   **Swap High-Calorie Items:** Replace some ingredients with lower-calorie,

In [47]:
voice_prompt = (
    "You are a meal‑planning assistant.\n"
    "• Write a friendly daily plan for the user in 4‑6 bullet points.\n"
    "• Mention each meal_slot and its dish.\n"
    "• End with one sentence on how today’s macros move toward the goals.\n\n"
    "### DATA\n"
    + json.dumps({"intent": intent_json, "meals": ranked_meals}, indent=2)
)

chat_reply = call_gemini(voice_prompt, temperature=0.55, max_tokens=220)
print(chat_reply)

Here is your meal plan for today:

*   **Breakfast**: Start your day with a hearty Oatmeal with Berries and Nuts.
*   **Lunch**: Enjoy a flavorful Lentil Soup with Whole-Wheat Bread and Salad.
*   **Dinner**: Savor a delicious Chicken Stir-fry with Brown Rice.
*   **Evening Snack**: Have Apple slices with Peanut Butter to satisfy your cravings.

This plan provides a good balance of protein, carbs, and fats to support your muscle gain goals.